### ISSUE TITLE
How to mock a Board for development with no hardware

### ISSUE THREAD

**Issue by testacode** [rwaldron/mock-firmata#7]
Hi,
I'm not an arduino (or similar clone) but I wanted to start coding something. Is there a way to use your mock for making the code below to work? thanks.

![image](https://user-images.githubusercontent.com/1852080/34913208-87b36b42-f8d5-11e7-81a8-c30bd78e6e31.png)

**Comment by dtex** [comment]
Hi @testacode 

I haven't personally tried it out in a few years, but there is this [hardware optional tutorial](https://www.npmjs.com/package/nodebot-workshop). It doesn't use mock-firmata but it lets you try stuff out without hardware.

Does that look like what you are looking for?

**Comment by testacode** [comment]
Mmm... I want to code a fermentator controlled system based on several other arduinos conecting to each other and passing the data to the base arduino. I'll try it and let you know. You can close this issue for now. Thanks @dtex !

**Comment by dtex** [comment]
I'll close it, but I may have misunderstood what you were looking for. I actually thought this was a different repo. 

The scenario you describe (several Arduino's connected to a "base" Arduino) can be done with using i2c backpacks, but depending on the requirements it might be easier to use a SBC (single board computer) as your base.

Please feel free to re-open this anytime. I don't really feel like I've given you a good starting place.
